# -*- coding: utf-8 -*-
"""Spotify Data Analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134fWTBndvRCFDn6D9653lrnNHJS1sUrC
"""

# Commented out IPython magic to ensure Python compatibility.
#import libraries for mathematical calculations
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

df_track = pd.read_csv("/content/SpotifyFeatures.csv")
df_track.head()

#info about data
df_track.info()

#checking null values
df_track.isnull().sum()

df_popular_sorted = df_track.sort_values('popularity', ascending = False)
df_popular_sorted.head(5)

most_popular = df_track.query('popularity > 90' , inplace = False).sort_values
most_popular

df_track.head()

#heatmap
plt.figure(figsize=(9,5))
sns.heatmap(df_track.corr(), annot=True)

sample_df = df_track.sample(int(0.004 * len(df_track)))

plt.figure(figsize = [9,6])
sns.regplot(data = sample_df, y= 'loudness', x='energy', color = 'c')

plt.figure(figsize=[9,6])
sns.regplot(data = sample_df, y='popularity', x='acousticness', color='g')

plt.figure(figsize = [16,7])
plt.title('Duration of the song in different generes')
sns.color_palette('rocket', as_cmap = True)
sns.barplot(y = 'genre', x = 'duration_ms', data = df_track)

sns.set_style(style='darkgrid')
plt.figure(figsize=[10,6])
most_popular_genres = df_track.sort_values('popularity', ascending = False)
sns.barplot(y='genre', x = 'popularity', data=most_popular_genres)

